language: c

os: linux

# Prepare the matrices for windows and linux compilation.
env:
  - PLATFORM=Linux ARCH=x86_64
  - PLATFORM=Windows ARCH=x86_64
  - PLATFORM=Linux ARCH=x86
  - PLATFORM=Windows ARCH=x86

# Create the OSX-specific matrix.
matrix:
  include:
    - os: osx
      env:
        PLATFORM=Darwin
        ARCH=x86_64

# Ensure that the scripts are executable.
before_install:
  - sudo chmod +x ./Scripts/*.sh
  - sudo chmod +x ./Scripts/Installers/*.sh

# Install rquired dependencies.
install:
  - bash ./Scripts/install.sh

# Build the application.
script:
  - ./Scripts/build.sh

# Deploy the resulting app.
deploy:
  # Deploy to amazon S3 bucket.
  - provider: s3
    access_key_id: AKIAIJKL4VT2ROHIZFSA
    secret_access_key:
      secure: "kjb4NbeaNNRPd4OgHPR3T7KOZ2j2tbmyJ6NQBmDwqQlCQCbZ2plFQ0bzKCOEbtiJLmIuWyOpxzy6TFk4Q7sdO1TegCDa4eKB9aB6zkrrIgDaFGoW3/Gy9X/iFH3lYb3eHs0NWOObndRP3riaYxX/Fbneqpl2H2wYtZMSC94d7yvy4LPFOWhhPZewVaJM7G85qpY+W/k209jRgn96cgwR9pcQKtj5B8jpKza//PE1pwqd/ghL2Md07qvSDc0nrtRQUzDa5HgG9M1E9hzApWsaHEKoIKOd94DjVixU3KtEV3BrCGbcs0G9na4C2tzG7ksOXrbg1dMAfzUXtn+KJkebSlMwPrjTAwZKnpJn729erny4uy8LqI37UBw3HakBUsaQMcSusP0Wdd+6d4qbLXo+jvMFJ+mbIdv7qq/7RcSJZ0sHgqJOyxfpYP9WJRtV6g/zWl2S6SvTXgSsu2PLo3CGmJH3LLmKiU9tSwlJ9gwueUtZ7wdyJxgP7adhI/kUzEKwdpArQOtvmXhIhi4KcjM2lZRJJ/pb8hC8tv0bySdMNuoOgHu4dggbdoHF+xS7uETfdYJsdK6do/q1Z7UenjmvB0H5tA4crqkLOdh9rst39iBpcJGU4N/jN/LTL5QoyRA78kyerHov2MscAFyy7/jv/zDAyvv3kySvW7Q638/MXu4="
    bucket: defi-t2.jb-caillaud.fr
    skip_cleanup: true
    acl: public_read
    region: eu-west-3
    upload-dir: Versions/${PLATFORM}
    local_dir: Build/out
    on:
      branch:
        - master
  
  # Deploy to github releases.
  - provider: releases
    api_key:
      secure: "YqM//QlE0IvL5k8YP55rT7IxaWIbc8x2+zSVzselRnaW/75U9YI+hWPGHsvXZJE67E6gsY2jpbwDDjbSkb1VCoLxlgrReY4f6twu/kUxsw1MBFquXuJB3/H6u5CSFiTzOfWOtlk8LxChN8FKrCv7s05ETNNhJte6zrr/kGLCshFNRGBRm2+wbhggjiN2NFC9nlxwWh+9FR7ds320OFxHVYlak+qi9fB197uE5GVFghlkRHSChiUjoUoaG2wV3+Wksj90WP5GeEuBtNzXnUVa5l4bp5jxH1sgoxiILAL1NjrS84lNoOpNSsRjUoMhyen0sq7F801Rvk9/ycV2ez2Rjs0TijhqnTpzu40gIpZ5gmcy4UE1qMZNfFRt0PpsCYxNTZG6vokIbEcKtAPM9wBGrB99NQML9YPIobqxa8cm6+nOEh4P1FYgilOD7qnw9gnjMRrWyiPTe6JWuIoY6ouY8ZOnM0+pMC0OYFGvpBN+6noKU8pRb/dxC2PBlciA8rWJNHhRScHbvcTfJWeRiySdgMWI716u5uuJ6wEXJtvQ1h3XB93ZghwdDKRKGFYkiXLaEaDBz7ATIBOgx/tX2Wps1+MlIthui4O2d2s9asWX6BT0vvseOml4mEzD6VHKvMeNKLnRDNjalG8A8mqhue31lCYXQUEjKcDzGo794DL/RyY="
    skip_cleanup: true
    file: "Build/out/PNC-${MAJOR}_${MINOR}_${TRAVIS_BUILD_NUMBER}-${PLATFORM}_${ARCH}.zip"
    on:
      tags: true